// This file contains a mapping of countries to their states/provinces
// It also indicates which countries have states and which don't

const countryStates = {
  // Countries with states/provinces
  "United States": {
    hasStates: true,
    states: [
      "Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", 
      "Delaware", "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", 
      "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts", "Michigan", 
      "Minnesota", "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada", "New Hampshire", 
      "New Jersey", "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio", "Oklahoma", 
      "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota", "Tennessee", 
      "Texas", "Utah", "Vermont", "Virginia", "Washington", "West Virginia", "Wisconsin", "Wyoming",
      "District of Columbia", "American Samoa", "Guam", "Northern Mariana Islands", "Puerto Rico",
      "United States Virgin Islands"
    ]
  },
  "Canada": {
    hasStates: true,
    states: [
      "Alberta", "British Columbia", "Manitoba", "New Brunswick", "Newfoundland and Labrador", 
      "Northwest Territories", "Nova Scotia", "Nunavut", "Ontario", "Prince Edward Island", 
      "Quebec", "Saskatchewan", "Yukon"
    ]
  },
  "Australia": {
    hasStates: true,
    states: [
      "Australian Capital Territory", "New South Wales", "Northern Territory", "Queensland", 
      "South Australia", "Tasmania", "Victoria", "Western Australia"
    ]
  },
  "India": {
    hasStates: true,
    states: [
      "Andhra Pradesh", "Arunachal Pradesh", "Assam", "Bihar", "Chhattisgarh", 
      "Goa", "Gujarat", "Haryana", "Himachal Pradesh", "Jharkhand", "Karnataka", 
      "Kerala", "Madhya Pradesh", "Maharashtra", "Manipur", "Meghalaya", "Mizoram", 
      "Nagaland", "Odisha", "Punjab", "Rajasthan", "Sikkim", "Tamil Nadu", 
      "Telangana", "Tripura", "Uttar Pradesh", "Uttarakhand", "West Bengal",
      "Andaman and Nicobar Islands", "Chandigarh", "Dadra and Nagar Haveli and Daman and Diu",
      "Delhi", "Jammu and Kashmir", "Ladakh", "Lakshadweep", "Puducherry"
    ]
  },
  "United Kingdom": {
    hasStates: true,
    states: [
      "England", "Northern Ireland", "Scotland", "Wales"
    ]
  },
  "Germany": {
    hasStates: true,
    states: [
      "Baden-Württemberg", "Bavaria", "Berlin", "Brandenburg", "Bremen", "Hamburg", 
      "Hesse", "Lower Saxony", "Mecklenburg-Vorpommern", "North Rhine-Westphalia", 
      "Rhineland-Palatinate", "Saarland", "Saxony", "Saxony-Anhalt", "Schleswig-Holstein", "Thuringia"
    ]
  },
  "Brazil": {
    hasStates: true,
    states: [
      "Acre", "Alagoas", "Amapá", "Amazonas", "Bahia", "Ceará", "Distrito Federal", 
      "Espírito Santo", "Goiás", "Maranhão", "Mato Grosso", "Mato Grosso do Sul", 
      "Minas Gerais", "Pará", "Paraíba", "Paraná", "Pernambuco", "Piauí", "Rio de Janeiro", 
      "Rio Grande do Norte", "Rio Grande do Sul", "Rondônia", "Roraima", "Santa Catarina", 
      "São Paulo", "Sergipe", "Tocantins"
    ]
  },
  "Mexico": {
    hasStates: true,
    states: [
      "Aguascalientes", "Baja California", "Baja California Sur", "Campeche", "Chiapas", 
      "Chihuahua", "Coahuila", "Colima", "Durango", "Guanajuato", "Guerrero", "Hidalgo", 
      "Jalisco", "México", "Michoacán", "Morelos", "Nayarit", "Nuevo León", "Oaxaca", 
      "Puebla", "Querétaro", "Quintana Roo", "San Luis Potosí", "Sinaloa", "Sonora", 
      "Tabasco", "Tamaulipas", "Tlaxcala", "Veracruz", "Yucatán", "Zacatecas"
    ]
  },
  "China": {
    hasStates: true,
    states: [
      "Anhui", "Beijing", "Chongqing", "Fujian", "Gansu", "Guangdong", "Guangxi", 
      "Guizhou", "Hainan", "Hebei", "Heilongjiang", "Henan", "Hong Kong", "Hubei", 
      "Hunan", "Inner Mongolia", "Jiangsu", "Jiangxi", "Jilin", "Liaoning", "Macau", 
      "Ningxia", "Qinghai", "Shaanxi", "Shandong", "Shanghai", "Shanxi", "Sichuan", 
      "Taiwan", "Tianjin", "Tibet", "Xinjiang", "Yunnan", "Zhejiang"
    ]
  },
  "Russia": {
    hasStates: true,
    states: [
      "Adygea", "Altai Krai", "Altai Republic", "Amur Oblast", "Arkhangelsk Oblast", 
      "Astrakhan Oblast", "Bashkortostan", "Belgorod Oblast", "Bryansk Oblast", 
      "Buryatia", "Chechen Republic", "Chelyabinsk Oblast", "Chukotka Autonomous Okrug", 
      "Chuvashia", "Dagestan", "Ingushetia", "Irkutsk Oblast", "Ivanovo Oblast", 
      "Jewish Autonomous Oblast", "Kabardino-Balkaria", "Kaliningrad Oblast", 
      "Kalmykia", "Kaluga Oblast", "Kamchatka Krai", "Karachay-Cherkessia", 
      "Karelia", "Kemerovo Oblast", "Khabarovsk Krai", "Khakassia", "Khanty-Mansi Autonomous Okrug", 
      "Kirov Oblast", "Komi", "Kostroma Oblast", "Krasnodar Krai", "Krasnoyarsk Krai", 
      "Kurgan Oblast", "Kursk Oblast", "Leningrad Oblast", "Lipetsk Oblast", 
      "Magadan Oblast", "Mari El", "Mordovia", "Moscow", "Moscow Oblast", 
      "Murmansk Oblast", "Nenets Autonomous Okrug", "Nizhny Novgorod Oblast", 
      "North Ossetia-Alania", "Novgorod Oblast", "Novosibirsk Oblast", "Omsk Oblast", 
      "Orenburg Oblast", "Oryol Oblast", "Penza Oblast", "Perm Krai", "Primorsky Krai", 
      "Pskov Oblast", "Rostov Oblast", "Ryazan Oblast", "Saint Petersburg", 
      "Sakha Republic", "Sakhalin Oblast", "Samara Oblast", "Saratov Oblast", 
      "Sevastopol", "Smolensk Oblast", "Stavropol Krai", "Sverdlovsk Oblast", 
      "Tambov Oblast", "Tatarstan", "Tomsk Oblast", "Tula Oblast", "Tver Oblast", 
      "Tyumen Oblast", "Tuva", "Udmurtia", "Ulyanovsk Oblast", "Vladimir Oblast", 
      "Volgograd Oblast", "Vologda Oblast", "Voronezh Oblast", "Yamalo-Nenets Autonomous Okrug", 
      "Yaroslavl Oblast", "Zabaykalsky Krai"
    ]
  },

  // Countries without states (or where states are not commonly used in addresses)
  "Afghanistan": { hasStates: false },
  "Albania": { hasStates: false },
  "Algeria": { hasStates: false },
  "Andorra": { hasStates: false },
  "Angola": { hasStates: false },
  "Antigua and Barbuda": { hasStates: false },
  "Argentina": { hasStates: true, states: ["Buenos Aires", "Catamarca", "Chaco", "Chubut", "Córdoba", "Corrientes", "Entre Ríos", "Formosa", "Jujuy", "La Pampa", "La Rioja", "Mendoza", "Misiones", "Neuquén", "Río Negro", "Salta", "San Juan", "San Luis", "Santa Cruz", "Santa Fe", "Santiago del Estero", "Tierra del Fuego", "Tucumán"] },
  "Armenia": { hasStates: false },
  "Austria": { hasStates: false },
  "Azerbaijan": { hasStates: false },
  "Bahamas": { hasStates: false },
  "Bahrain": { hasStates: false },
  "Bangladesh": { hasStates: false },
  "Barbados": { hasStates: false },
  "Belarus": { hasStates: false },
  "Belgium": { hasStates: false },
  "Belize": { hasStates: false },
  "Benin": { hasStates: false },
  "Bhutan": { hasStates: false },
  "Bolivia": { hasStates: false },
  "Bosnia and Herzegovina": { hasStates: false },
  "Botswana": { hasStates: false },
  "Brunei": { hasStates: false },
  "Bulgaria": { hasStates: false },
  "Burkina Faso": { hasStates: false },
  "Burundi": { hasStates: false },
  "Cambodia": { hasStates: false },
  "Cameroon": { hasStates: false },
  "Cape Verde": { hasStates: false },
  "Central African Republic": { hasStates: false },
  "Chad": { hasStates: false },
  "Chile": { hasStates: false },
  "Colombia": { hasStates: false },
  "Comoros": { hasStates: false },
  "Congo": { hasStates: false },
  "Costa Rica": { hasStates: false },
  "Croatia": { hasStates: false },
  "Cuba": { hasStates: false },
  "Cyprus": { hasStates: false },
  "Czech Republic": { hasStates: false },
  "Denmark": { hasStates: false },
  "Djibouti": { hasStates: false },
  "Dominica": { hasStates: false },
  "Dominican Republic": { hasStates: false },
  "East Timor": { hasStates: false },
  "Ecuador": { hasStates: false },
  "Egypt": { hasStates: false },
  "El Salvador": { hasStates: false },
  "Equatorial Guinea": { hasStates: false },
  "Eritrea": { hasStates: false },
  "Estonia": { hasStates: false },
  "Eswatini": { hasStates: false },
  "Ethiopia": { hasStates: false },
  "Fiji": { hasStates: false },
  "Finland": { hasStates: false },
  "France": { hasStates: false },
  "Gabon": { hasStates: false },
  "Gambia": { hasStates: false },
  "Georgia": { hasStates: false },
  "Ghana": { hasStates: false },
  "Greece": { hasStates: false },
  "Grenada": { hasStates: false },
  "Guatemala": { hasStates: false },
  "Guinea": { hasStates: false },
  "Guinea-Bissau": { hasStates: false },
  "Guyana": { hasStates: false },
  "Haiti": { hasStates: false },
  "Honduras": { hasStates: false },
  "Hungary": { hasStates: false },
  "Iceland": { hasStates: false },
  "Indonesia": { hasStates: false },
  "Iran": { hasStates: false },
  "Iraq": { hasStates: false },
  "Ireland": { hasStates: false },
  "Israel": { hasStates: false },
  "Italy": { hasStates: false },
  "Jamaica": { hasStates: false },
  "Japan": { hasStates: false },
  "Jordan": { hasStates: false },
  "Kazakhstan": { hasStates: false },
  "Kenya": { hasStates: false },
  "Kiribati": { hasStates: false },
  "North Korea": { hasStates: false },
  "South Korea": { hasStates: false },
  "Kuwait": { hasStates: false },
  "Kyrgyzstan": { hasStates: false },
  "Laos": { hasStates: false },
  "Latvia": { hasStates: false },
  "Lebanon": { hasStates: false },
  "Lesotho": { hasStates: false },
  "Liberia": { hasStates: false },
  "Libya": { hasStates: false },
  "Liechtenstein": { hasStates: false },
  "Lithuania": { hasStates: false },
  "Luxembourg": { hasStates: false },
  "Madagascar": { hasStates: false },
  "Malawi": { hasStates: false },
  "Malaysia": { hasStates: false },
  "Maldives": { hasStates: false },
  "Mali": { hasStates: false },
  "Malta": { hasStates: false },
  "Marshall Islands": { hasStates: false },
  "Mauritania": { hasStates: false },
  "Mauritius": { hasStates: false },
  "Micronesia": { hasStates: false },
  "Moldova": { hasStates: false },
  "Monaco": { hasStates: false },
  "Mongolia": { hasStates: false },
  "Montenegro": { hasStates: false },
  "Morocco": { hasStates: false },
  "Mozambique": { hasStates: false },
  "Myanmar": { hasStates: false },
  "Namibia": { hasStates: false },
  "Nauru": { hasStates: false },
  "Nepal": { hasStates: false },
  "Netherlands": { hasStates: false },
  "New Zealand": { hasStates: false },
  "Nicaragua": { hasStates: false },
  "Niger": { hasStates: false },
  "Nigeria": { hasStates: false },
  "Norway": { hasStates: false },
  "Oman": { hasStates: false },
  "Pakistan": { hasStates: false },
  "Palau": { hasStates: false },
  "Panama": { hasStates: false },
  "Papua New Guinea": { hasStates: false },
  "Paraguay": { hasStates: false },
  "Peru": { hasStates: false },
  "Philippines": { hasStates: false },
  "Poland": { hasStates: false },
  "Portugal": { hasStates: false },
  "Qatar": { hasStates: false },
  "Romania": { hasStates: false },
  "Rwanda": { hasStates: false },
  "Saint Kitts and Nevis": { hasStates: false },
  "Saint Lucia": { hasStates: false },
  "Saint Vincent and the Grenadines": { hasStates: false },
  "Samoa": { hasStates: false },
  "San Marino": { hasStates: false },
  "Sao Tome and Principe": { hasStates: false },
  "Saudi Arabia": { hasStates: false },
  "Senegal": { hasStates: false },
  "Serbia": { hasStates: false },
  "Seychelles": { hasStates: false },
  "Sierra Leone": { hasStates: false },
  "Singapore": { hasStates: false },
  "Slovakia": { hasStates: false },
  "Slovenia": { hasStates: false },
  "Solomon Islands": { hasStates: false },
  "Somalia": { hasStates: false },
  "South Africa": { hasStates: false },
  "South Sudan": { hasStates: false },
  "Spain": { hasStates: false },
  "Sri Lanka": { hasStates: false },
  "Sudan": { hasStates: false },
  "Suriname": { hasStates: false },
  "Sweden": { hasStates: false },
  "Switzerland": { hasStates: false },
  "Syria": { hasStates: false },
  "Taiwan": { hasStates: false },
  "Tajikistan": { hasStates: false },
  "Tanzania": { hasStates: false },
  "Thailand": { hasStates: false },
  "Togo": { hasStates: false },
  "Tonga": { hasStates: false },
  "Trinidad and Tobago": { hasStates: false },
  "Tunisia": { hasStates: false },
  "Turkey": { hasStates: false },
  "Turkmenistan": { hasStates: false },
  "Tuvalu": { hasStates: false },
  "Uganda": { hasStates: false },
  "Ukraine": { hasStates: false },
  "United Arab Emirates": { hasStates: false },
  "Uruguay": { hasStates: false },
  "Uzbekistan": { hasStates: false },
  "Vanuatu": { hasStates: false },
  "Vatican City": { hasStates: false },
  "Venezuela": { hasStates: false },
  "Vietnam": { hasStates: false },
  "Yemen": { hasStates: false },
  "Zambia": { hasStates: false },
  "Zimbabwe": { hasStates: false }
};

export default countryStates;